### PR TITLE
Finish renaming bazelbuild/buildifier to bazelbuild/buildtools.

### PR DESCRIPTION
**Pull request by hochhaus**
Change generated with:

```bash
grep -rl bazelbuild/buildifier . | xargs -I {} sed -i 's/bazelbuild\/buildifier/bazelbuild\/buildtools/g' {}
```

### CODE REVIEW

**Comment by pmbethe09** [comment]
This seems to be an updated version of 
https://github.com/bazelbuild/buildtools/pull/90 which lay fallow.

Let me look at it

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Comment by hochhaus** [comment]
Thanks, I had overlooked #90.

**Comment by pmbethe09** [comment]
No worries -- you fixed some doc that I had missed.

**Pull request merged**
