### PR TITLE
Update the test suite to run all tests separately with --format_bzl

### PR DESCRIPTION
**Pull request by vladmos**
Currently only test cases with a `.formatbzl.golden` file are tested with `--format_bzl`.

With this change all test cases are tested with and without the `--format_bzl` flag. If there's no special `.formatbzl.golden` file, the `.golden` file is used in both cases.

Idempotence tests are also run with and without the flag. If there's a `.formatbzl.golden` counterpart for a given `.golden` file, this file is not tested for idempotence with the flag. The opposite is not true: `.format.golden` files are tested for idempotence with and without the flag.

### CODE REVIEW

**Comment by vladmos** [comment]
Jenkins, retest this please

**Comment by vladmos** [comment]
Jenkins, retest this please

**Comment by vladmos** [comment]
Jenkins, retest this please

**Comment by laurentlb** [comment]
lgtm

**Comment by vladmos** [comment]
Jenkins, retest this please

**Comment by vladmos** [comment]
Jenkins, retest this please

**Comment by vladmos** [comment]
I'm going to merge, the tests are failing only on Ubuntu 14.04 due to an error in our CI.

**Pull request merged**
