### PR TITLE
Make Gazelle happy with the checked in generated code.

### PR DESCRIPTION
**Pull request by mattmoor**
See: https://github.com/kubernetes/test-infra/pull/4859#issuecomment-347749178 for more context.

Related: https://github.com/bazelbuild/buildtools/issues/14

### CODE REVIEW

**Comment by mattmoor** [comment]
@ianthehat Is this what you meant?

**Comment by mattmoor** [comment]
@pmbethe09 @laurentlb @damienmg FYI

**Comment by ianthehat** [comment]
Yes

**Comment by laurentlb** [comment]
LGTM
Thanks

**Comment by mattmoor** [comment]
@ianthehat I'm seeing this in the `kubernetes/test-infra` repo when I try to consume this:
```
# gazelle:exclude parse.y.go
go_library(
    name = "go_default_library",
    srcs = [
        "lex.go",
        "parse.y.baz.go",  # keep
        "parse.y.go",   <-- Gazelle put this in
        "print.go",
        "quote.go",
        "rewrite.go",
        "rule.go",
        "syntax.go",
        "walk.go",
    ],
    importpath = "github.com/bazelbuild/buildtools/build",
    visibility = ["//visibility:public"],
    deps = ["//vendor/github.com/bazelbuild/buildtools/tables:go_default_library"],
)
```

**Comment by ianthehat** [comment]
I will defer to @jayconrod the gazelle expert at this point...

**Comment by jayconrod** [comment]
The `# gazelle:exclude` directive should be near the top of the file, before the first statement. Gazelle should print a warning when you run it.

**Pull request merged**
