### PR TITLE
add tests for AddValueToListAttribute

### PR DESCRIPTION
**Pull request by swolchok**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by swolchok** [comment]
> CLA

This contribution is being made on behalf of my employer, Facebook.

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Comment by swolchok** [comment]
ping

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Pull request merged**
