### PR TITLE
Fix missing files in npm distribution

### PR DESCRIPTION
**Pull request by alexeagle**
@vladmos I'll add the missing testing to this PR as well. Just wanted to get it here quickly in case you want to merge and re-release now before the tests are ready.

### CODE REVIEW

**Comment by vladmos** [comment]
Released 2.2.1 with this fix.

**Comment by alan-agius4** [comment]
@vladmos, it seems that `2.2.1` has not released.

```
npm dist-tags @bazel/buildifier
latest: 2.2.0
```

**Comment by vladmos** [comment]
Thanks for telling it, the release process for npm is not yet automatized. I'll try to release it asap once a minor problem with it is resolved.

In the future it should be released to Github and NPM (almost) simultaneously.

**Comment by vladmos** [comment]
@alan-agius4 2.2.1 has just been released to npm, please let me know if there are any issues with it.

**Comment by alan-agius4** [comment]
Thanks @vladmos!

**Pull request merged**
