### PR TITLE
Introduce an add_raw command

### PR DESCRIPTION
**Pull request by WillerZ**
Resolves: #565

Some of the build-rule functions used within Facebook are higher-order functions that accept lists of parameters which are not basic strings. This change to buildozer allows me to programmatically insert new values of this type into those rules without introducing duplicates.

### CODE REVIEW

**Comment by WillerZ** [comment]
I should be an authorized contributor covered by our corporate agreement

**Comment by WillerZ** [comment]
I really am an authorized contributor and I should be covered by our corporate agreement

**Comment by laurentlb** [comment]
I wonder if there can be a different interface, without introducing a new command. I expect other people will need `set_raw`, `set_raw_if_absent`, `replace_raw`, `dict_add_raw`, `dict_set_raw`.

**Comment by WillerZ** [comment]
@laurentlb You're right of course, and I expect I'll need most of those sooner or later.

I tried (quite briefly I admit) and couldn't come up with something else that would be perfectly backwards compatible and not risk breaking existing scripts. Best I came up with is some "magic" prefix to the string parameter like `^` to mean "this is raw" but I don't have enough context on other people's builds to know if that character choice would be safe enough.

**Comment by vladmos** [comment]
Would it make sense to add a new flag (like `--raw_input` that would be applied to all commands (`add`, `set`, `set_if_absent`, `replace`, `dict_add`, `dict_set`)?

**Comment by WillerZ** [comment]
I'm abandoning this PR.

The workaround we're using is to use `add` to insert `"wanted_part_REMOVE_THE_QUOTES_AND_THIS_MESSAGE"` and chasing that with two perl one-liners that remove the duplicate entries and the quotes.

**Pull request closed without merging**
