### PR TITLE
Replace global edit.Opts with a local variable

### PR DESCRIPTION
**Pull request by cgrushko**
Motivation: make it safer to run multiple edit.Buildozer() commands simultanously.

### CODE REVIEW

**Comment by cgrushko** [comment]
@pmbethe09 @laurentlb

**Comment by cgrushko** [comment]
This will probably break internal customers - I'm happy to modify them together with the CL that imports this PR.

**Comment by pmbethe09** [comment]
LGTM

**Comment by cgrushko** [comment]
I don't have edit permissions, can you merge this?

**Pull request merged**
