### PR TITLE
Fall back to x86_64 binary when run tools via rules_nodejs on Apple silicon

### PR DESCRIPTION
**Pull request by thii**

### CODE REVIEW

**Comment by thii** [comment]
cc @alexeagle

**Comment by keith** [comment]
Can we just build a arm64 binary instead? we should be unblocked to do that at this point right?

**Comment by thii** [comment]
Does rules_go support that yet?

**Comment by thii** [comment]
Looks like the latest of it does.

**Comment by thii** [comment]
https://github.com/bazelbuild/buildtools/pull/994

**Pull request closed without merging**
