### PR TITLE
Add missing repo boundary files

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@Wyverald Could you review this as well?

**Review by Wyverald — APPROVED** [review]

**Comment by fmeum** [comment]
@vladmos I fixed one test failure in the buildifier integration test, but I don't understand the test setup for the remaining `another_test_dir` failure to the extent required to fix the new failure caused by that fix.

**Comment by fmeum** [comment]
The Windows failure seems unrelated.

**Comment by fmeum** [comment]
I fixed the CI failures.

**Pull request merged**
