### PR TITLE
Add publishing to npm

### PR DESCRIPTION
**Pull request by alexeagle**
This replaces the mirroring we currently do in https://github.com/bazelbuild/rules_nodejs/blob/master/scripts/mirror_buildtools.sh

### CODE REVIEW

**Comment by alexeagle** [comment]
Note, I can't find anywhere in the repo that you use `--stamp` to create your existing release, so I'm not sure where to add the command to publish these packages.

Let me know where to add those...

**Comment by vladmos** [comment]
The releases are currently created by Buildkite and a script there is supposed to use `--stamp` (however probably it doesn't because the latest versions of buildifier and buildozer fail to print the correct version when called with `--version`).

I'm going to rewrite the release script anyway, meanwhile perhaps you can create a .bazelrc file like the one for bazelisk.

**Comment by alexeagle** [comment]
@vladmos thanks, added a release.sh that has just the npm bits for now

**Comment by vladmos** [comment]
Thanks!

**Comment by mdvorsky** [comment]
Hi! We use buildifier in our WORKSPACE and we fetch it from master (as recommended in https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md).

It looks like after this PR, buildifier stopped working and we had to both:
- Upgrade bazel_skylib to at least 0.8
- Add build_bazel_rules_nodejs to our WORKSPACE

Especially the second change is surprising, because we don't use build_bazel_rules_nodejs in our WORKSPACE at all, but somehow, buildifier doesn't bring that dependency on its own.

It looks like that build_bazel_rules_nodejs is both missing from buildifier deps.bzl and the instructions to install buildifier to the WORKSPACE are missing the call to buildifier_dependencies().

**Comment by vladmos** [comment]
There's an issue for this: #796

**Pull request merged**
