### PR TITLE
Stop moving distribs from a function to the package.

### PR DESCRIPTION
**Pull request by aiuto**
Stop moving `distribs()` from a function to the `package()`

- `distribs` is being removed.
- We probably should stop moving licenses as well.

This PR address part of #1224.  We can decide if we want to fling the entire move now or do licenses in a separate PR.

### CODE REVIEW

**Comment by aiuto** [comment]
CI seems to be broken on windows because of a C++ tooling change

**Comment by aiuto** [comment]
cc: @teeler

**Comment by aiuto** [comment]
Friendly ping.

**Comment by larsrc-google** [comment]
Vlad, could you take a look at this, please?

**Comment by aiuto** [comment]
@teeler  Should we stop moving licenses also?

**Comment by vladmos** [comment]
LGTM. Should I merge now or wait for the decision regarding licenses?

**Review by vladmos — APPROVED** [review]

**Comment by aiuto** [comment]
Let's merge now.

**Comment by aiuto** [comment]
The failing tests seem to be windows toolchain specific.

**Review by vladmos — APPROVED** [review]

**Pull request merged**
