### PR TITLE
buildifier2: support lambda expressions

### PR DESCRIPTION
**Pull request by fenollp**
Note that in my own usage of buildifier2 the example I provided gets `build.FormatString`-ed onto just one line:
```starlark
TriggerActionAfterProbe(probe = ("http", "response"), predicate = lambda State, response: all([response["request"]["method"] == "GET", response["request"]["url"].find("/posts/") != -1, response["request"]["url"].endswith("/comments"), response["status_code"] in range(200, 299)]), action = lambda State, response: None)
```
I wonder what's different with this test suite. And now writing all this I'm guessing either
* my code isn't being exercised by the tests, or
* the tests use different formatting settings
I'll look into it (any ideas though?)

Anyway, buildifier2 would crash without this clause.

### CODE REVIEW

**Comment by pmbethe09** [comment]
AFAIK starlark does not support lambda expressions

https://docs.bazel.build/versions/master/skylark/language.html#differences-with-python

**Comment by fenollp** [comment]
True, Bazel's Starlark does not support lambdas, however they are defined in [this spec](https://github.com/google/starlark-go/blob/e55f603d8c797b182566012861c5784481d00df4/doc/spec.md#lambda-expressions) and implemented in the Go version of the interpreter.
Also, you've reviewed PRs relating to lambda expressions (#860) so I'm not sure why you mention this?

cc #852

**Comment by vladmos** [comment]
Buildifier now supports lambda expressions, but as buildifier2 is experimental and not being maintained I didn't fix lambda expressions there.

**Review by vladmos — APPROVED** [review]
Thanks!

**Pull request merged**
