### PR TITLE
Added s390x arch support

### PR DESCRIPTION
**Pull request by Repana-Chowdappa**
Currently buildtools repo doesn't a downloadable s390x binary yet for buildifier, buildozer. I tried to build buildtools on s390x and it actually builds fine. Need to include s390x arch binaries in https://github.com/bazelbuild/buildtools/releases/.

### CODE REVIEW

**Comment by Repana-Chowdappa** [comment]
@vladmos @pmbethe09 @larsrc-google  - Can you please check and approve this PR.

**Comment by Repana-Chowdappa** [comment]
@vladmos @pmbethe09 @larsrc-google - This is blocking rules_rust and kong CI completion for s390x arch to add s390x support. Buildifier is dependency for rust_rules and kong. Please help us in reviewing this PR.

**Review by lysliu — APPROVED** [review]
LGTM

**Review by vladmos — APPROVED** [review]
Thanks!

**Comment by rchowdap** [comment]
@vladmos @lysliu - Thanks for merging the PR to code base. May i know when will be next release for buildtools and when s390x buildifier binary available for us.

**Comment by vladmos** [comment]
I'll cut a new release in an hour.

**Comment by Repana-Chowdappa** [comment]
@vladmos - I don't see s390x binaries on https://github.com/bazelbuild/buildtools/releases/download/v7.3.1/ after new release. Please let us know whether s390x binaries are built or not.

**Comment by vladmos** [comment]
The binaries were not configured for Github releases. I uploaded them this time manually, #1289 is a permanent fix.

**Pull request merged**
