### PR TITLE
Fix empty `package()` calls appearing in non-BUILD files

### PR DESCRIPTION
**Pull request by fmeum**
Caused by https://github.com/bazelbuild/buildtools/commit/9c3c1fc0106ed2174f1a7c4a322a08f0a553bc1e, but only relevant if users use the pseudo-target `__pkg__` with non-BUILD files as recommended for file-level operations.

Work towards #1149 
Work towards https://github.com/bazelbuild/bazel/issues/17908

### CODE REVIEW

**Comment by fmeum** [comment]
@laurentlb I observed this small regression caused by my last commit when I tried to use `//MODULE.bazel:__pkg__` to skip per-target fixes.

I will try to follow up with a change that provides a more direct way to achieve the same goal.

**Comment by Wyverald** [comment]
is there precedent for editing other non-BUILD files? I find the syntax `//MODULE.bazel:__pkg__` very unappealing. I'm guessing that `//:MODULE.bazel` is off the table since it would try to edit the `MODULE.bazel` target in the `BUILD` file?

**Comment by fmeum** [comment]
`//MODULE.bazel:all` also works and is what I am currently using. Maybe we could make `//MODULE.bazel` work? It *could* also be referring to a `bazel_dep(name = "MODULE.bazel")` though.

**Comment by Wyverald** [comment]
> Maybe we could make `//MODULE.bazel` work? It _could_ also be referring to a `bazel_dep(name = "MODULE.bazel")` though.

Did you maybe mean `java_library(name = "MODULE.bazel")` or something? I didn't know that each individual `bazel_dep` could be referred to.

**Comment by fmeum** [comment]
> Did you maybe mean `java_library(name = "MODULE.bazel")` or something? I didn't know that each individual `bazel_dep` could be referred to.

From the point of view of buildozer, all rules are the same. As long as your tags have a `name` attribute, you can even operate on them. We are using this to emit migration commands in Gazelle that look like this:

```
new go_deps.gazelle_override gopkg.in/yaml.v3|//MODULE.bazel:all
add directives gazelle:go_naming_convention\ go_default_library|//MODULE.bazel:gopkg.in/yaml.v3
rename name path|//MODULE.bazel:gopkg.in/yaml.v3
remove build_naming_convention|//MODULE.bazel:%go_deps.module
remove build_file_proto_mode|//MODULE.bazel:%go_deps.module
```

But having anything in `MODULE.bazel` with `name = "MODULE.bazel"` would still be very weird.

**Comment by Wyverald** [comment]
Ah I see. I guess my main gripe is that `//MODULE.bazel:foo` changes the `foo` "target" in the file `/MODULE.bazel`, instead of the `foo` target in the file `/MODULE.bazel/BUILD`.

I think I'd prefer a special syntax, something like `//:__module__`, for the MODULE.bazel file. That means you'd need difference syntax to operate on the stuff in there, but we're already kind of doing that (with `use_repo_add`, for example).

**Comment by fmeum** [comment]
@vladmos Could you take a look at this fix? I would submit a separate PR that proposes special syntax to identify the `MODULE.bazel` file.

**Pull request merged**
