### PR TITLE
Also detect LiteralExprs as UsedSymbols.

### PR DESCRIPTION
**Pull request by varomodt**
The unusedLoads fixer doesn't work for some BZL files b/c it removes used
symbols which contain a constant (e.g. my_import.CONSTANT) since UsedSymbols
only detects *build.Ident. This CL adds detection of potential imported
symbols from LiteralExprs to UsedSymbols.

Internal bug: b/110991860

### CODE REVIEW

**Comment by laurentlb** [comment]
`my_import.CONSTANT` should be parsed as a `DotExpr` (https://github.com/bazelbuild/buildtools/blob/master/build/syntax.go#L189). `LiteralExprs` are not supposed to include dots.

**Comment by varomodt** [comment]
Well, I see them as LiteralExprs experimentally: Were it a DotExpr, we would recurse in and see an Ident I think. Maybe that should be a separate issue?

**Comment by laurentlb** [comment]
Parser looks correct to me: https://github.com/bazelbuild/buildtools/blob/master/build/parse.y#L433

Either there's a bug, or something else modifies the AST. Can you double-check?

**Comment by varomodt** [comment]
Retracting this PR, as it was a result of an error in internal code.

**Pull request closed without merging**
