### PR TITLE
Warning against overriding some global attributes in rules.

### PR DESCRIPTION
**Pull request by aiuto**
Add lint warnings against naming attributes 'licenses', 'applicable_licenses', or 'package_metadata'.  Using any of those can cause unexpected behaviors when generating SBOMs.

### CODE REVIEW

**Comment by aiuto** [comment]
cc: @teeler  This would have caught the problem from yesterday.

**Comment by aiuto** [comment]
Friendly ping

**Comment by aiuto** [comment]
Friendly ping

**Comment by aiuto** [comment]
Another week, another ping.

**Review by laurentlb — APPROVED** [review]

**Comment by vladmos** [comment]
@aiuto Sorry for the delay, the PR was lost in my backlog.

@laurentlb it will be enabled internally by default (however that can be overridden). I'd keep them enabled unless there's a good reason for using these attributes internally.

**Comment by aiuto** [comment]
We want this check enabled internally. That was the motivation. A rule declaration with an attribute named `licenses` was causes SBOM generation to break for targets which transitively used that rule.

**Pull request merged**
