### PR TITLE
Fixes build for Windows

### PR DESCRIPTION
**Pull request by meteorcloudy**
Fixes https://github.com/bazelbuild/buildtools/issues/1210

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Turns out it's a long path issue on Windows.

**Comment by meteorcloudy** [comment]
After this one, we still need to update rules_go to fix downstream breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3592#018d0add-494c-4c59-b452-da6cd582688c

**Review by vladmos — APPROVED** [review]
Thanks!

**Comment by meteorcloudy** [comment]
@vladmos Can you please try to update rules_go to fix the breakage with Bazel@HEAD?
```
(04:01:30) ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9e21fb089b9da2ba3a2c9233fa8beaa3/external/io_bazel_rules_go/go/private/rules/transition.bzl", line 126, column 47, in _go_transition_impl
		platform = platform_from_crosstool(crosstool_top, cpu)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9e21fb089b9da2ba3a2c9233fa8beaa3/external/io_bazel_rules_go/go/platform/crosstool.bzl", line 57, column 27, in platform_from_crosstool
		platform = matcher(crosstool_top, cpu)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9e21fb089b9da2ba3a2c9233fa8beaa3/external/io_bazel_rules_go/go/platform/crosstool.bzl", line 38, column 21, in _match_android
		crosstool_top.workspace_name == "androidndk":
Error: 'NoneType' value has no field or method 'workspace_name'
```

**Comment by vladmos** [comment]
@meteorcloudy Updated in #1234

**Pull request merged**
