### PR TITLE
Detect pants workspace

### PR DESCRIPTION
**Pull request by illicitonion**
Pants uses the existence of an executable file named pants to detect its workspace root.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by illicitonion** [comment]
Ping? @laurentlb?

**Comment by laurentlb** [comment]
Sorry for the delay. We'll take a look at this next week (I've been busy recently, and there are issues to synchronize github with our internal codebase).

**Comment by laurentlb** [comment]
LGTM

**Pull request merged**
