### PR TITLE
Do not warn about repeated loads in WORKSPACE file

### PR DESCRIPTION
**Pull request by chsigg**
WORKSPACE files allow load() statements that are not at the top, and the imports can shadow previous ones.

This change restricts the 'symbol already loaded' warning to non-WORKSPACE files.

### CODE REVIEW

**Comment by laurentlb** [comment]
Sure, symbol redefinition is allowed in workspace files, but that doesn't mean it's a good idea. I would personally discourage this pattern.

**Comment by chsigg** [comment]
> Sure, symbol redefinition is allowed in workspace files, but that doesn't mean it's a good idea. I would personally discourage this pattern.

I see your point that redefinition might be considered bad style, and buildifier does not fix it incorrectly but only warns about it.

How about adding a different warning for redefinitions? E.g. "Symbol %q has already been defined on line %d. Please use a different name."

**Comment by vladmos** [comment]
There is a warning for redefined variables: https://github.com/bazelbuild/buildtools/blob/master/warn/warn_control_flow_test.go#L352

Is that what you mean?

Regarding this PR, I agree that the warning makes sense even if shadowing is allowed. In most cases it will confuse the reader if the symbols you need happen to have the same name you can disambiguate by using an alias:

    load("...", "name1")
    load("...", name2 = "name1)

Or, if you need to shadow, suppress the warning with a comment: https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#suppress

**Comment by chsigg** [comment]
I'm suggesting to have two different warnings when load() shadows a previous symbol:

```
load("foo", "foo")
load("foo", "foo")  # warning: symbol 'foo' has already been loaded on line 1. Please remove it.
load("bar", "foo")  # warning: a different symbol 'foo' has already been loaded on line 1. Please use a different local name.
```

Currently, both cases will report the first warning, but it's not very accurate for the second case.

Note: I'm no longer suggesting to handle WORKSPACE files differently. You convinced me that emitting a warning is appropriate.

**Review by vladmos — APPROVED** [review]

**Pull request merged**
