### PR TITLE
Accept either WORKSPACE or .buckconfig as indicating repo root.

### LINKED ISSUE #93: buildozer: WORKSPACE search is surprising for Buck users
Buck doesn't have an equivalent to Bazel's `WORKSPACE` files. Normally, this isn't a problem -- the search fails and buildozer assumes `$PWD` is the root directory. Because Mac OS uses a case-insensitive filesystem, this causes surprising behavior for buildozer+Buck users who happen to have a file or directory called `workspace` in their home directory (e.g., because they've used Eclipse).

Passing `-root_dir .` (and running from the Buck root) is a workaround, but it's not an obvious one; the same seems true for adding an otherwise-unnecessary `WORKSPACE` file to the Buck root. Perhaps there is something we can do in Buildozer to make using it easier for Buck users?

### PR DESCRIPTION
**Pull request by swolchok**
Fixes #93.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by swolchok** [comment]
I think the CLA should be fixed now? not sure.

**Comment by swolchok** [comment]
Hmm, maybe there's some latency in the CLA system? I commented pretty quick after I was told the problem had been resolved on our end.

**Comment by laurentlb** [comment]
LGTM, thanks!

**Pull request merged**
