### PR TITLE
Command 'replace' works on expressions containing lists

### PR DESCRIPTION
**Pull request by cgrushko**

### CODE REVIEW

**Comment by cgrushko** [comment]
@pmbethe09

**Comment by cgrushko** [comment]
@laurentlb

**Comment by pmbethe09** [comment]
Should we fix the build first?

**Comment by cgrushko** [comment]
I really only need this to unblock an internal migration - fixing the build on github is slightly outside my path :)
I built the project manually after removing the hash lines from 3 places in the WORKSPACE file.

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Comment by cgrushko** [comment]
@pmbethe09  ping :)

**Pull request merged**
